### ISSUE TITLE
Doesn't recognize state change after initial load (during run time)

### ISSUE THREAD

**Issue by m0rganic** [nrswolf/cordova-plugin-push-notifications-status#1]
@nrswolf Looks like a really useful plugin, thanks for your contribution!

I'm building a push notifications settings screen in my app and would like to notify iOS users to head over to the Notification Center when the app detects push is disabled. 

I'm building it with ionic angular framework and have wrapped your cordova plugin with an angular service. The problematic behavior I'm seeing is that the plugin doesn't recognize state changes to the system notification setting unless I restart the app. 

Are you able to verify this works without app restarts?

**Comment by m0rganic** [comment]
nevermind, doesn't seem to be an issue any more, thanks again for the simple plugin!

**Comment by russellw-dev** [comment]
@m0rganic hi! Just FYI I've found the easiest way to use this is as a top-level function in ionic's application.js:

``` js
if (window.cordova) {
  setInterval(function() {
    PushNotificationsStatus.isPushNotificationsEnabled(function(response) {
      window.localStorage.isPushNotificationsEnabled = response;
    })
  }, 500);
}
```

Then functions inside angular controllers, services etc. can just check localstorage to determine if push notifications are enabled.

**Comment by m0rganic** [comment]
I did something slightly more complex. This solution will allow you to limit running the interval call (which makes an expensive system call) to a small window when it's relevant to your app (i.e. on your settings screen, in-app push notifications setting screen, etc..).

Since I'm developing on ionic so the interval api looks slightly different.. Also I'm wrapping your plugin with a service (see below) to return promises and cast the string result ('true' and 'false') to a boolean primitive.

``` javascript
if (ionic.Platform.isIOS()) {
  $scope.stopPushChecking = $interval(function() {
    iOSPushNotificationStatus.checkIfEnabled()
      .then(function(result) {
        $scope.pushToggle.show = result; // pushEnabled should be boolean
      }, function(error) {});
  }, 1000);
}
```

Later in that same controller where you need it, you can cancel the background interval thread, which is friendlier to the device.

``` javascript
$scope.$on("$destroy", function(event) {
  if ($scope.stopPushChecking) {
    $interval.cancel($scope.stopPushChecking);
  }
});
```

My service that wraps this plugin with a promise and casts result from string to a boolean.

``` javascript
angular.module('services', ['ionic', 'ngCordova'])

.factory('iOSPushNotificationStatus', function($window, $q) {
  var deferred = undefined;
  var successHandler = function(response) {
    if (typeof response === 'string') {
      // coerce the string into a boolean
      deferred.resolve(response == 'true' ? true : false);
    } else if (typeof response === 'boolean') {
      deferred.resolve(response);
    } else {
      errorHandler('successHandler couldnt parse type');
    }
  };
  var errorHandler = function(error) {
    deferred.reject(error);
  };
  return {
    checkIfEnabled: function() {
      deferred = $q.defer()
      PushNotificationsStatus.isPushNotificationsEnabled(successHandler, errorHandler);
      return deferred.promise;
    }
  }
});

```
