### ISSUE TITLE
Migrate plugin to npm

### ISSUE THREAD

**Issue by utamanna** [nrswolf/cordova-plugin-push-notifications-status#2]
Hi!

This plugin does exactly what we want and would love to continue using it.

The Cordova plugins registry is [moving](http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html) its plugins to NPM and October 15th is when they shutdown the plugins access on their site.

If you want I can migrate the plugin over to [NPM](npmjs.com), or if you have already moved the plugin to NPM please share a link to it because I couldn't find it on there.

Please let me know if I can help with this.

Thanks!

**Comment by bau720123** [comment]
hi @nrswolf 
just like @usman8806 said
move to npm is very helpful

**Comment by russellw-dev** [comment]
@usman8806 @bau720123 sorry guys, yup I'll move it to NPM when I get a chance in the next couple of days.  In the meantime you can clone the repo and install it from there source via cordova

**Comment by bau720123** [comment]
thanks @nrswolf 
awesome

**Comment by russellw-dev** [comment]
@usman8806 @bau720123 moved to NPM (see README) - thanks for letting me know.

**Comment by bau720123** [comment]
thanks @nrswolf

**Comment by utamanna** [comment]
Awesome! Thanks @nrswolf.
