### ISSUE TITLE
Support for iOS 9.0 - replace deprecated APIs

### ISSUE THREAD

**Issue by ricolo** [nrswolf/cordova-plugin-push-notifications-status#3]
@nrswolf Thank you for this plugin. Some APIs used in this plugin are deprecated in the latest iOS version. Would you please add support for them? Below are the Xcode warning messages when I compile the project:

```
'UIRemoteNotificationType' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead.

'enabledRemoteNotificationTypes' is deprecated: first deprecated in iOS 8.0 - Please use -[UIApplication isRegisteredForRemoteNotifications], or -[UIApplication currentUserNotificationSettings] to retrieve user-enabled remote notification and user notification settings

'UIRemoteNotificationTypeAlert' is deprecated: first deprecated in iOS 8.0 - Use UIUserNotificationType for user notifications and registerForRemoteNotifications for receiving remote notifications instead.
```

**Comment by russellw-dev** [comment]
@ricolo Sure, I can find some time this week to take care of it. Any chance you might be able to open a PR on it if you need it sooner?

**Comment by ricolo** [comment]
Hi @nrswolf I just looked at your code and realized that you may have covered iOS 8+ in the first if-statement (not 100% sure since I can't code in Objective-C), and the second if-statement is for backward compatibility, so this would be merely an issue with suppressing the deprecation warning when compiling in Xcode.

If this is the case, I will close this issue.
